language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UslLR67qhp3yCUmS3Rd0Ik1GdEvTYSyMUJXSIWcK11tnxllbC8YbNWO9RUEIJQM2t3pKYN2Fcd1tfgrRurEF7IK3Wu/Etw5I8TSlrCsMSUllisZ4FhCq4d/I9tewSnXmjMMUfXtzPQ2oO2XmiJaFk2wnNpBwlvbTGIy5HofyN0fFgsgKdC01BaSkUOjyWiza8sjHfPf+u9NWwx8IbFoImFhuq0K6pJLpBjy2eNBt3WDbL8/MLzQ361lNk8x1BAm54SSSNpCW3xzoKk9D3Dh0Q0P2BLAn0OeEKY/vdnrLIA+InkH3vg/MLHkMW/gZTsxVubY8M4pFEOzK5duLOwn9aVX4wlydzk7orZqfFlD6x7ouss3m8RDUHlgvbe/6tTYkdNE6d63I2tfzDq0N6twsK8p72QLan+kbha24nYmladjt2moBa4rz0nyWAwvH9WCzceRNy1WhpwpTPvPMQeu7cWghsxHLFF5OZOCjdBF99ny3L2YzgcaSrMfJ7+slS1hX8VR+JJtcS2HpVyLKFI3SkXiQqikhGUQbSqb49wE7u/4QnYQbRY4QoeVboEO2GcGx+8V//OqeC8LjrS+4sF5dCJYSFxm619m/Gn/eP0GUO5JjtvC8dLlTdK87JgxmHZ1ytmmc+9mh0gmGa2Mrr28ujm/PeZxIOG9oHjOuVly4bqA=
  file:
    - "remark-inline-links.js"
    - "remark-inline-links.min.js"
  on:
    tags: true
